/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package General_Purpose_IDE.app;

import java.awt.*;

import General_Purpose_IDE.GUI.JDS6600_GUI;
import General_Purpose_IDE.GUI.MenuBar;
import General_Purpose_IDE.GUI.Terminal;
import bibliothek.gui.dock.common.*;

import javax.swing.*;

public class App {
    public static void main( String[] args ){
        initializeApp();
    }

    private static void initializeApp() {
        //initialize terminal
        Terminal.getComponent();

        //initialize interpreter
        Interpreter.init();

        //create application GUI
        createGUI();


    }

    private static void createGUI() {
        /* creating a frame and a control */
        JFrame frame = new JFrame();
        CControl control = new CControl( frame );
        frame.setDefaultCloseOperation( JFrame.EXIT_ON_CLOSE );
        frame.add(control.getContentArea(), BorderLayout.CENTER);

        CGrid grid = new CGrid(control);

        /* creating some menus... */
//        JMenuBar menubar = MenuBar.getComponent();
//        frame.setJMenuBar( menubar );

        //create terminal
        SingleCDockable terminal = Terminal.getComponent();
        Terminal.setAsOutputStream();
//        Terminal.setAsErrorStream();


        //create CWorkingArea
        CWorkingArea workingArea = new CWorkingArea(control, "workspace");


        //components that will be added to workingArea
//        SingleCDockable JDS6600_component = JDS6600_GUI.getComponent();


        grid.add(0, 0, 1, 1, workingArea);
        grid.add(0, 1, 1, 1, terminal);

        //set components visible
        terminal.setVisible(true);

        //must deploy before CControl registered with working area
        CContentArea content = control.getContentArea();
        content.deploy(grid);

        //add stuff to workingArea
//        workingArea.add(JDS6600_component);
        workingArea.setVisible(true);
//        workingArea.show(JDS6600_component);

        frame.setBounds(20, 20, 400, 400);
        frame.setVisible(true);

//        System.out.println("test 1");
//        System.out.println("test 2");
    }

}